### ISSUE TITLE
Future of Whisperpush

### ISSUE THREAD

**Issue by yate** [CyanogenMod/android_external_whispersystems_WhisperPush#17]
Looking at the comments near the end of this review http://review.cyanogenmod.org/#/c/98015/, it seems like Whisperpush is no more, is that true? 

`"We're moving to a SMS app with TS built in cm-13.0 according to ciwrl."`

Does anyone have more details, or know where to get future updates about this topic?

Thank you

**Comment by scottwallacesh** [comment]
I've just installed CM13.0 and noticed that WhisperPush is now missing.  I'd be interested to see what's going on with this now.

**Comment by yate** [comment]
I found commit https://github.com/CyanogenMod/android_packages_apps_Messaging/commit/939a4c8552b17e062a2 which shows they are integrating it into Messaging.  I have no idea when it will be in cm-13.0 though, it's been in the staging branch for a month now. 

Maybe @dshkil could shed some light?

**Comment by yate** [comment]
http://www.cyanogenmod.org/blog/whisperpush-end-of-life

I guess that answers that.
