### ISSUE TITLE
Functionality?  TextSecure and CM?

### ISSUE THREAD

**Issue by tripflex** [CyanogenMod/android_external_whispersystems_WhisperPush#7]
So I can't find really anything regarding using the integrated WhisperPush and I know it's still under active development, but can anybody confirm where the functionality is at right now?

If i'm using CM with WP enabled, will it work between my device and someone else who is only using the TextSecure app?  

I tested it and was able to get it to work correctly between two phones that were running CM with WP enabled, but haven't gotten much farther than that.  

What about key exchange messages?  Does someone using TS have to initiate it to me and then WP will automatically complete the exchange?  Are there plans to add functionality to allow through WP to send key exchange?

Just trying to see where the project is at now, as I am using CM but seems like of like overkill having to use Text Secure as well, but maybe that's what's needed right now until WP is further along in development?  Thanks!

**Comment by moxie0** [comment]
There still isn't a TextSecure release which supports the push channel available.  Next release, they should talk to each other.

It's not recommended to have both WP and TS enabled on the same device.

**Comment by generalmanager** [comment]
@tripflex TextSecure V2 has been released some time now.

The communication between TS and WhisperPush should be encrypted from the first message onwards.
The whole key exchange message stuff was only used for SMS in the old TS version.
TS V2 should behave just like another WhisperPush contact.
If this answers your questions, could you close this ticket? Thanks

**Comment by tripflex** [comment]
ah didn't realize this was still open, but yeah i've been enjoying it since the day it was released.  Like the new design more than stock messaging so I actually use the text secure app instead of regular messaging app on CM.

Great stuff Moxie, btw love the Hold Fast video you have on your blog very cool video to watch!
